site_name: ka-sarthak's website
site_description: Thoughts and musings of a software engineer
site_url: https://ka-sarthak.github.io/
repo_url: https://github.com/ka-sarthak/website
repo_name: "ka-sarthak/website"