name: Deploy website

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build and Deploy
        env:
          ACTIONS_GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          mkdocs build
          git clone https://github.com/ka-sarthak/ka-sarthak.github.io.git
          cd ka-sarthak.github.io
          git config user.email "sarthakkapoor@hotmail.com"
          git config user.name "Sarthak Kapoor"
          rm -rf *
          cp -r ../site/* .
          git add .
          git commit -m "Automatic deployment"
          git push https://ka-sarthak:${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/ka-sarthak/ka-sarthak.github.io.git
          cd ..
          rm -rf ka-sarthak.github.io